### ISSUE TITLE
polis.conf file: maxconnection variable not being observed

### ISSUE THREAD

**Issue by LinuxETC** [polispay/polis#87]
### Describe the issue
Within the `.poliscore/polis.conf` file one can set `maxconnections` with a limitation (e.g., `maxconnection=32`).  I am noticing via `watch -d2 "polis-cli getinfo"` (so a "real time" and updated display of this information) that the number of connections is actually high than the posted limit (e.g., low 40's).

### Can you reliably reproduce the issue?
I am seeing this issue across multiple and different Masternode VPS systems. 

### Expected behaviour
I would expect with the `maxconnection` variable set in the `.poliscore/polis.conf` file, this limitation to be observed and NOT exceeded.  

### Actual behaviour
I have observed with the `maxconnection` variable set ("32" in my case) in the `.poliscore/polis.conf` file, this limitation is exceeded to 40+ connections via `polis-cli getinfo`.

### What version of Polis Core are you using?
Via `polis-cli getinfo` I see `"version": 1041100,` noted.

This was hand compiled from Github, v1.4.11 within 24 hours of it being announced and available on Ubuntu 16.04LTS versus the provided binary release version.

### Machine specs:
- OS:  Ubuntu 16.04LTS
- CPU: x1 core
- RAM: 4GB RAM
- Disk size: N/A
- Disk Type (HD/SDD): N/A

**Comment by hlooman** [comment]
I am observing the exact same problem.
In fact, I have a node experiencing extreme traffic now due to a very large number of connections, exceeding the maxconnection setting.

# polis-cli getinfo
{
  "version": 1041100,
  "protocolversion": 70214,
  "walletversion": 61000,
  "balance": 0.00000000,
  "blocks": 340179,
  "timeoffset": 0,
  "connections": 263,
  "proxy": "",
  "difficulty": 10.64184894716678,
  "testnet": false,
  "keypoololdest": 1537318019,
  "keypoolsize": 1000,
  "paytxfee": 0.00000000,
  "relayfee": 0.00001000,
  "errors": ""
}

Ubuntu 16.04LTS

**Comment by LinuxETC** [comment]
Observed in v1.4.13 of code as well.

**Comment by LinuxETC** [comment]
Observed in v1.4.18 of code as well.
